---
- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: create bashrc.d directory
    ansible.builtin.file:
      path: ~/.bashrc.d
      state: directory

  - name: bashrc
    copy:
      src: files/bash_aliases
      dest: ~/.bashrc.d/test_stuff

  - name: install required software
    become: true
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: present
    loop:
      - telnet
      - jq
      - net-tools
